apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: null
  name: tail
spec:
  description: |-
    Kail https://github.com/boz/kail - "Just show me the logs"

    Stream logs from all matched containers of all matched pods.  Match pods by service,
    replicaset, deployment, and others.  Adjusts to a changing cluster - pods are
    added and removed from logging as they fall in or out of the selection.

    Documentation:

      See https://github.com/boz/kail or

      $ kubectl tail --help

    Usage:

      # match all pods
      $ kubectl tail

      # match pods in the 'frontend' namespace
      $ kubectl tail --ns staging

      # match pods belonging to a replicaset named 'workers' in any namespace.
      $ kubectl tail --rs workers

      # match pods belonging to the replicaset named 'workers' only in the 'staging' namespace
      $ kubectl tail --rs staging/workers

      # match pods belonging to both the service "frontend" and the deployment "webapp"
      $ kubectl tail --svc frontend --deploy webapp
  homepage: https://github.com/boz/kail
  platforms:
  - bin: kail
    files:
    - from: kail
      to: .
    - from: LICENSE.txt
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 976c22cb56ebbe496a29ebf1e271637095eaa95bf345df6d1a34efbe1e963ee4
    uri: https://github.com/boz/kail/releases/download/v0.15.0/kail_0.15.0_darwin_amd64.tar.gz
  - bin: kail
    files:
    - from: kail
      to: .
    - from: LICENSE.txt
      to: .
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: e37862bf4547329a3299aece4ae62bc7d3a277cafeadc81304c262a016816ce2
    uri: https://github.com/boz/kail/releases/download/v0.15.0/kail_0.15.0_linux_amd64.tar.gz
  shortDescription: Stream logs from multiple pods and containers using simple, dynamic
    source selection.
  version: v0.15.0
status:
  source:
    name: default
